name: flutter_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  pdf: ^1.7.1
  printing: ^3.3.1
  image: ^2.1.4
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/OpenSans-Bold.ttf
        - asset: assets/OpenSans-BoldItalic.ttf
        - asset: assets/OpenSans-Italic.ttf
        - asset: assets/OpenSans-Regular.ttf